export const SHOW_PROGRESS_BAR   = 'SHOW_PROGRESS_BAR';
export const HIDE_PROGRESS_BAR   = 'HIDE_PROGRESS_BAR';

export const SHOW_SNACKBAR       = 'SHOW_SNACKBAR' ;
export const HIDE_SNACKBAR       = 'HIDE_SNACKBAR' ;

export const ENABLE_FORM_INPUTS  = 'ENABLE_FORM_INPUTS';
export const DISABLE_FORM_INPUTS = 'DISABLE_FORM_INPUTS';

export const USER_AUTH_ATTEMPT   = 'USER_AUTH_ATTEMPT';
export const USER_AUTH_CHECK     = 'USER_AUTH_CHECK';
export const USER_AUTH_FAIL      = 'USER_AUTH_FAIL';
export const USER_AUTH_SUCCESS   = 'USER_AUTH_SUCCESS';
export const USER_AUTH_LOGOUT    = 'USER_AUTH_LOGOUT';

export const PATIENTS_FETCH      = 'PATIENTS_FETCH';
export const PATIENTS_FETCHED    = 'PATIENTS_FETCHED';
