export const SHOW_PROGRESS_BAR   = 'SHOW_PROGRESS_BAR';
export const HIDE_PROGRESS_BAR   = 'HIDE_PROGRESS_BAR';

export const SHOW_ERROR_MESSAGE  = 'SHOW_ERROR_MESSAGE' ;
export const HIDE_ERROR_MESSAGE  = 'HIDE_ERROR_MESSAGE' ;

export const ENABLE_FORM_INPUTS  = 'ENABLE_FORM_INPUTS';
export const DISABLE_FORM_INPUTS = 'DISABLE_FORM_INPUTS';

export const USER_AUTH_ATTEMPT   = 'USER_AUTH_ATTEMPT';
export const USER_AUTH_FAIL      = 'USER_AUTH_FAIL';
export const USER_AUTH_SUCCESS   = 'USER_AUTH_SUCCESS';
export const USER_AUTH_LOGOUT    = 'USER_AUTH_LOGOUT';
