export const SHOW_PROGRESS_BAR = 'SHOW_PROGRESS_BAR';
export const HIDE_PROGRESS_BAR = 'HIDE_PROGRESS_BAR';

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';

export const ENABLE_FORM_INPUTS = 'ENABLE_FORM_INPUTS';
export const DISABLE_FORM_INPUTS = 'DISABLE_FORM_INPUTS';

export const PATIENT_CARD_TOGGLE_EDIT_FORM = 'PATIENT_CARD_TOGGLE_EDIT_FORM';

export const USER_AUTH_ATTEMPT = 'USER_AUTH_ATTEMPT';
export const USER_AUTH_CHECK = 'USER_AUTH_CHECK';
export const USER_AUTH_REFRESH = 'USER_AUTH_REFRESH';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT';

export const PATIENTS_FETCH = 'PATIENTS_FETCH';
export const PATIENTS_FETCHED = 'PATIENTS_FETCHED';

export const PATIENT_FETCH = 'PATIENT_FETCH';
export const PATIENT_FETCHED = 'PATIENT_FETCHED';
export const PATIENT_UPDATE = 'PATIENT_UPDATE';

export const REPORTS_FETCH = 'REPORTS_FETCH';
export const REPORTS_FETCHED = 'REPORTS_FETCHED';