export const START_HTTP = 'START_HTTP';
export const COMPLETE_HTTP = 'COMPLETE_HTTP';

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';

export const ENABLE_FORMS = 'ENABLE_FORMS';
export const DISABLE_FORMS = 'DISABLE_FORMS';

export const USER_AUTH_ATTEMPT = 'USER_AUTH_ATTEMPT';
export const USER_AUTH_CHECK = 'USER_AUTH_CHECK';
export const USER_AUTH_REFRESH = 'USER_AUTH_REFRESH';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT';

export const PATIENTS_FETCH = 'PATIENTS_FETCH';
export const PATIENTS_FETCHED = 'PATIENTS_FETCHED';

export const PATIENT_FETCH = 'PATIENT_FETCH';
export const PATIENT_FETCHED = 'PATIENT_FETCHED';

export const REPORTS_FETCH = 'REPORTS_FETCH';
export const REPORTS_FETCHED = 'REPORTS_FETCHED';
